#!/usr/bin/env python
import os
import time
import iso8601
import novaclient.v1_1.client as nvclient
import keystoneclient.v2_0.client as ksclient

from horizon.mail import send_mail
from django.utils import datetime_safe
#from datetime import *

#import glanceclient

def get_keystone_creds():
    d = {}
    d['username'] = os.environ['OS_USERNAME']
    d['password'] = os.environ['OS_PASSWORD']
    d['auth_url'] = os.environ['OS_AUTH_URL']
    d['tenant_name'] = os.environ['OS_TENANT_NAME']
    return d

def get_nova_creds():
    d = {}
    d['username'] = os.environ['OS_USERNAME']
    d['api_key'] = os.environ['OS_PASSWORD']
    d['auth_url'] = os.environ['OS_AUTH_URL']
    d['project_id'] = os.environ['OS_TENANT_NAME']
    return d


if __name__ == '__main__':
    creds = get_keystone_creds()
    keystone = ksclient.Client(**creds)

    creds = get_nova_creds()
    nova = nvclient.Client(**creds)

    while True:
        charge_subscriptions = nova.charge_subscriptions.list()
        for sub in charge_subscriptions: 
            if sub.item == "physical_server" and sub.status == "verified" and sub.expires_at and sub.resource_uuid:
	        now = datetime_safe.datetime.now().isoformat()
                #expires_time = iso8601.parse_date(sub.expires_at) 
		#frist_warning_time = (expires_time - timedelta(days=3)).isoformat()
		#second_warning_time = (expires_time - timedelta(days=2)).isoformat()
		#third_warning_time = (expires_time - timedelta(days=1)).isoformat()
     
		if sub.expires_at > now:
		    nova.charge_subscriptions.update(sub.id, status='terminated')
		    nova.charge_subscriptions.delete(sub.id)
		    nova.physical_servers.update(sub.resource_uuid, subscription_id='NULL')
		    #Send people mail
                    applier_mail_perfix = keystone.get(sub.user_id).name
                    #TODO by sunxin
                    applier_mail = applier_mail_perfix + '@lenovo.com'

                    mail_title = "[Notice] Server Restore"
                    mail_content = " Sorry, the server you used is out of date, and restored by Lab Administrator.\n Any qeustion, please send mail to sunxin3@lenovo.com.\n Thank you for your understanding."
                    send_mail(mail_title, mail_content, applier_mail)

        time.sleep(10)
